CREATE TABLE meeting
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    description      VARCHAR(255),
    date             date,
    room_id          BIGINT,
    max_participants INTEGER                                 NOT NULL,
    CONSTRAINT pk_meeting PRIMARY KEY (id)
);